# Site settings
title: Lusheep Blog
SEOTitle: Lusheep的博客 | Android 技术屋
header-img: img/home-bg.jpg
email: gm.lusheep@gmail.com
description: "关于自定义View、Android开发、Java | lusheep, custom view, Android technology, Java | 这里是 @lusheep 的个人博客，博客在手，说走就走"
keyword: "Lusheep, ViewInMyHeart, 自定义View, android开发, java,  java web, 博客, 个人网站, 开心阳"
url: "http://lusheep.me"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:    liaoluyang
zhihu_username:     lusheep
github_username:    lusheep

facebook_username:  lusheep



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
gems: [jekyll-paginate]



# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
# disqus_username:your_disqus_short_name

# Duoshuo settings

# duoshuo_username: 

duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: fb7d82dcae3d6c5fb554159904eec66e
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx

# ga_domain: lusheep.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "生活中只有一种英雄主义，那就是在认清生活真相之后依然热爱生活。。"
sidebar-avatar: http://avatar.csdn.net/1/0/4/1_shakespeare001.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps

chrome-tab-theme-color: "#000000"

service-worker: true



# Friends
friends: [
    {
        title: "开心阳",
        href: "http://blog.csdn.net/shakespeare001"
    },{
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "Ling's Blog",
        href: "http://linglinyp.com/"
    }
]
